SELECT ?members ?bandName where {,
            ?band dbo:genre dbr:Punk_rock .,
            ?band dbp:currentMembers ?members .,
            ?band foaf:name ?bandName,
            FILTER(langMatches(lang(?bandName), "en")),
}